### ISSUE TITLE
Crash when on new todo and clicking "ME" tab

### ISSUE THREAD

**Issue by sweigerd** [lubaochuan/RN-ToDoList#1]
Crash occurs when user is in the TodoEdit screen for a new todo item, and the user selects the ME tab.

Create new todo, but do not save.
Click out of the keyboard.
Click "ME" tab.

Error message:
"JSON.stringify cannot serialize cyclic structures."

**Comment by lubaochuan** [comment]
Issue fix in [this commit](https://github.com/lubaochuan/RN-ToDoList/commit/6da45cedfa67bfc85cfa418505e1b06343515582). The app crashes because react-navigation uses redux implicitly for tracking navigation - the app state contains references to components and components reference the state (circular structure). Major refactoring was done to make react-navigation use redux explicitly following [this example](https://github.com/lubaochuan/RN-ToDoList/commit/082743a3a655906ddda2bd711d343820505c8d91).
